<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EvalToolkit.Core\EvalToolkit.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Polly" />
    <PackageReference Include="Microsoft.Identity.Client" />
    <PackageReference Include="Microsoft.Identity.Client.Extensions.Msal" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="EvalToolkit.WorkIQ.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
